# Generated by Django 2.1.1 on 2018-10-10 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=64, unique=True)),
                ('site_msg', models.CharField(max_length=64, null=True)),
                ('site_url', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32, unique=True)),
                ('project_msg', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publist_ip', models.CharField(max_length=64)),
                ('Publist_dir', models.CharField(max_length=128)),
                ('Publist_msg', models.CharField(max_length=128, null=True)),
                ('current_version', models.CharField(max_length=64, null=True)),
                ('version_info', models.CharField(max_length=512, null=True)),
                ('author', models.CharField(max_length=64, null=True)),
                ('Publist_date', models.CharField(max_length=64, null=True)),
                ('Publist_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_code.GitMG')),
            ],
        ),
        migrations.CreateModel(
            name='PublistRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_version', models.CharField(max_length=64, null=True)),
                ('version_info', models.CharField(max_length=1024, null=True)),
                ('author', models.CharField(max_length=64, null=True)),
                ('Publist_date', models.CharField(max_length=64, null=True)),
                ('Publist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_code.Publist')),
            ],
        ),
        migrations.CreateModel(
            name='WchartReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_name', models.CharField(max_length=64, null=True)),
                ('from_user', models.CharField(max_length=64, null=True)),
                ('up_connect', models.CharField(max_length=2048, null=True)),
                ('up_id', models.CharField(max_length=64, null=True)),
                ('status', models.CharField(default='waiting', max_length=64)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='gitmg',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_code.Project'),
        ),
    ]
