# Generated by Django 2.1.1 on 2019-01-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcode',
            name='git_language',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
