# Generated by Django 2.1.1 on 2018-10-10 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_code', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_name', models.CharField(max_length=64, unique=True)),
                ('git_msg', models.CharField(max_length=64, null=True)),
                ('git_url', models.CharField(max_length=128, unique=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_code.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='gitmg',
            name='project',
        ),
        migrations.AlterField(
            model_name='publist',
            name='Publist_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_code.GitCode'),
        ),
        migrations.DeleteModel(
            name='GitMG',
        ),
    ]
