# Generated by Django 2.1.1 on 2018-10-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_code', '0003_auto_20181010_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publist',
            old_name='Publist_dir',
            new_name='publist_dir',
        ),
        migrations.RenameField(
            model_name='publist',
            old_name='Publist_ip',
            new_name='publist_ip',
        ),
        migrations.RenameField(
            model_name='publist',
            old_name='Publist_msg',
            new_name='publist_msg',
        ),
    ]
