# Generated by Django 2.1.1 on 2018-10-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_code', '0004_auto_20181010_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publist',
            old_name='Publist_date',
            new_name='publist_date',
        ),
    ]
