# Generated by Django 2.1.1 on 2018-10-10 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0001_initial'),
        ('app_code', '0006_auto_20181010_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publist',
            name='publist_ip',
        ),
        migrations.AddField(
            model_name='publist',
            name='host_ip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_asset.Host'),
            preserve_default=False,
        ),
    ]
