# Generated by Django 2.1.1 on 2018-10-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_code', '0008_auto_20181010_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WchartReq',
            new_name='Wchartlog',
        ),
    ]
