# Generated by Django 2.1.1 on 2018-10-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_code', '0009_auto_20181010_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitcode',
            name='git_sshkey',
            field=models.TextField(null=True),
        ),
    ]
