# Generated by Django 2.1.1 on 2018-10-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_code', '0010_auto_20181022_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publistrecord',
            name='current_version',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
