# Generated by Django 2.1.1 on 2018-10-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_code', '0011_auto_20181024_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publistrecord',
            name='current_version',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
