# Generated by Django 2.1.1 on 2018-10-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_code', '0012_auto_20181026_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publist',
            name='current_version',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
