# Generated by Django 2.1.1 on 2018-10-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_code', '0013_auto_20181026_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publist',
            name='current_version',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
