# Generated by Django 2.1.1 on 2018-10-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0002_hostdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostdetail',
            old_name='mem_total',
            new_name='mem_size',
        ),
    ]
