# Generated by Django 2.1.1 on 2018-10-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0003_auto_20181015_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdetail',
            name='interface',
            field=models.TextField(null=True),
        ),
    ]
