# Generated by Django 2.1.1 on 2018-10-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0005_auto_20181015_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_status',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
