# Generated by Django 2.1.1 on 2018-10-15 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0006_host_host_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=256)),
                ('server_version', models.CharField(max_length=512, null=True)),
                ('server_port', models.CharField(max_length=1026, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_asset.Host')),
            ],
        ),
    ]
