"""
Django settings for saltops_v2 project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

import djcelery
djcelery.setup_loader()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n@!t!m(okei_f(!sexwhk@co0ilc=@a1l!z!7rvq408rnw*&k4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'djcelery',
    'app_auth',
    'app_asset',
    'app_code',
    'app_sys',
    'app_tool',
    'app_log',
    'app_db',
]

MIDDLEWARE = [
   # 'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'django.middleware.cache.FetchFromCacheMiddleware',
]

ROOT_URLCONF = 'saltops_v2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'saltops_v2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'saltops_v2',
        'USER':'root',
        'PASSWORD':'mysql',
        'HOST':'192.168.1.126',
        'PORT':'3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#自定义登录认证中间件
AUTHENTICATION_BACKENDS = (
    'app_auth.views.CustomBackend',
)


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR,'statics')]


MEDIA_ROOT = os.path.join(BASE_DIR, 'statics','media')


MEDIA_URL = '/media/'


#登录认证url
LOGIN_URL = '/auth/login/'


SESSION_SAVE_EVERY_REQUEST = True

# 关闭浏览器，则COOKIE失效
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

#30分钟
SESSION_COOKIE_AGE = 60 * 60 * 24


#服务器软件列表
SERVER_TAG = ['php', 'nginx', 'redis', 'mysql', 'python', 'java','sshd']

#编程语言列表
LANGUAGE_LIST = ["Java","PHP","JavaScript","Objective-C","Android","C#","Python","Go",
                 "C++","HTML","C","NodeJS","Swift","Ruby","微信","TypeScript","HTML/CSS",
                 "Shell","Docker","CSS","Lua","C/C++","Kotlin","Scala","Delphi","Matlab",
                 "ActionScript","Dart","TeX/LaTeX","其他"]

ANSIBLE_USER ="opadmin"

MTROPS_HOST = "192.168.1.126"


#webssh 访问地址
WEBSSH_URL = "http://192.168.1.126:8000/"


#redis 服务信息
REDIS_INFO = {"host":"192.168.1.126", "port":6379}

#代码运行用户
CODE_RUNAS = "www"

PHPMYADMIN_URL = "http://192.168.1.126/phpmyadmin/"

#inception备份服务器登录密码
BACKDB_PASSWD="mysql"

#使用redis作为消息队列代理
#BROKER_URL = 'redis://192.168.1.126:6379/0'
#使用rabbitmq作为消息队列代理（推荐）
BROKER_HOST = "192.168.1.192"
BROKER_PORT = 5672
BROKER_USER = "onepeople"
BROKER_PASSWORD = "123456"
BROKER_VHOST = "/"
#使用resit作为数据存储
CELERY_RESULT_BACKEND = 'redis://192.168.1.126:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
#celery 结果有效期
CELERY_TASK_RESULT_EXPIRES  = 3600


#企业微信配置
WCHART_URL = 'https://qyapi.weixin.qq.com'
WCHART_CORPID = 'ww99fb*********'
WCHART_CORPSECRET = 'RKBH0e**************************'
WCHART_ADMIN_UDSER = 'LiZ****'


#阿里云用户访问权限ID

REGION_ID = "cn-shenzhen"

MTR_ACCESS_KEY_ID = "LTAI******3"
MTR_ACCESS_KEY_SECRET = "3RkSRrcOta******************"

MTY_ACCESS_KEY_ID = "LTAIC**************m2"
MTY_ACCESS_KEY_SECRET = "GQolNZw*****************I1BiR"

#memcached缓存
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyLibMCCache',  # 指定缓存使用的引擎
        'LOCATION':'192.168.1.126:11211',         # 指定本机的11211端口为Memcache缓存服务器
        }
}
