# Generated by Django 2.1.1 on 2018-12-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvSofeware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sofeware_name', models.CharField(max_length=128)),
                ('sofeware_version', models.CharField(max_length=128, null=True)),
                ('install_script', models.TextField(null=True)),
            ],
        ),
    ]
