# Generated by Django 2.1.1 on 2018-10-11 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sys', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnvInstall',
            new_name='EnvSofeware',
        ),
    ]
