# Generated by Django 2.1.1 on 2018-10-09 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=64)),
                ('menu_url', models.CharField(max_length=64, null=True)),
                ('menu_type', models.CharField(max_length=64)),
                ('pmenu_id', models.CharField(max_length=64, null=True)),
                ('menu_num', models.CharField(max_length=32, null=True)),
                ('menu_icon', models.CharField(max_length=256, null=True)),
                ('menu_order', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perms', models.CharField(max_length=64)),
                ('perms_msg', models.CharField(max_length=128, null=True)),
                ('menus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auth.Menus')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=64, unique=True)),
                ('role_msg', models.CharField(max_length=128, null=True)),
                ('menu', models.ManyToManyField(to='app_auth.Menus')),
                ('perms', models.ManyToManyField(to='app_auth.Perms')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32, unique=True)),
                ('ready_name', models.CharField(max_length=64, null=True)),
                ('passwd', models.CharField(max_length=256, null=True)),
                ('email', models.CharField(max_length=64, null=True)),
                ('phone', models.CharField(max_length=128, null=True)),
                ('img', models.ImageField(null=True, upload_to='img')),
                ('status', models.CharField(default='离线', max_length=64)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('role', models.ManyToManyField(to='app_auth.Role')),
            ],
        ),
    ]
