# Generated by Django 2.1.1 on 2018-10-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menus_title', models.CharField(max_length=64)),
                ('menus_url', models.CharField(max_length=64)),
                ('menus_level', models.CharField(max_length=32)),
                ('menus_order', models.CharField(max_length=32)),
                ('pmenu_id', models.CharField(max_length=32, null=True)),
                ('menus_id', models.CharField(max_length=32, null=True)),
                ('menus_icon', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Perms', models.CharField(max_length=64)),
                ('Perms_msg', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=64, unique=True)),
                ('role_msg', models.CharField(max_length=128, null=True)),
                ('perms', models.TextField()),
                ('menu', models.ManyToManyField(to='app_auth.Menus')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('ready_name', models.CharField(max_length=64, null=True)),
                ('passwd', models.CharField(max_length=256, null=True)),
                ('email', models.CharField(max_length=64, null=True)),
                ('phone', models.CharField(max_length=128, null=True)),
                ('img', models.ImageField(upload_to='img')),
                ('status', models.CharField(max_length=64, null=True)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('role', models.ManyToManyField(to='app_auth.Role')),
            ],
        ),
        migrations.AddField(
            model_name='menus',
            name='menus_perms',
            field=models.ManyToManyField(to='app_auth.Perms'),
        ),
    ]
