# Generated by Django 2.1.1 on 2018-12-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='/static/img/user/11.jpg', upload_to='img'),
        ),
    ]
