# Generated by Django 2.1.1 on 2018-10-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perms',
            old_name='perms',
            new_name='perms_req',
        ),
        migrations.RemoveField(
            model_name='perms',
            name='perms_msg',
        ),
        migrations.AddField(
            model_name='perms',
            name='perms_title',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
