# Generated by Django 2.1.1 on 2018-10-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_auto_20181009_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
