# Generated by Django 2.1.1 on 2018-10-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_auto_20181007_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='menus_perms',
        ),
        migrations.AddField(
            model_name='menus',
            name='menus_perms',
            field=models.ManyToManyField(to='app_auth.Perms'),
        ),
    ]
