# Generated by Django 2.1.1 on 2018-10-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='perms',
            name='perms_url',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
