# Generated by Django 2.1.1 on 2018-10-07 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_auto_20181007_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='menus_level',
        ),
        migrations.RemoveField(
            model_name='menus',
            name='menus_order',
        ),
        migrations.RemoveField(
            model_name='menus',
            name='pmenu_id',
        ),
        migrations.AddField(
            model_name='menus',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_auth.Menus'),
        ),
    ]
