# Generated by Django 2.1.1 on 2018-10-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_auto_20181007_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='perms',
            field=models.TextField(null=True),
        ),
    ]
