# Generated by Django 2.1.1 on 2018-10-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_asset', '0001_initial'),
        ('app_auth', '0005_auto_20181012_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='asset',
        ),
        migrations.AddField(
            model_name='role',
            name='host',
            field=models.ManyToManyField(to='app_asset.Host'),
        ),
        migrations.AddField(
            model_name='role',
            name='netwk',
            field=models.ManyToManyField(to='app_asset.Netwk'),
        ),
    ]
