# Generated by Django 2.1.1 on 2018-10-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0006_auto_20181012_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='project',
            field=models.ManyToManyField(to='app_code.GitCode'),
        ),
    ]
