# Generated by Django 2.1.1 on 2018-10-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0006_auto_20181008_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='perms',
        ),
        migrations.AddField(
            model_name='role',
            name='perms',
            field=models.ManyToManyField(to='app_auth.Perms'),
        ),
    ]
