# Generated by Django 2.1.1 on 2018-10-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0007_auto_20181008_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perms',
            old_name='Perms',
            new_name='perms',
        ),
        migrations.RenameField(
            model_name='perms',
            old_name='Perms_msg',
            new_name='perms_msg',
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
