# Generated by Django 2.1.1 on 2018-10-22 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0007_auto_20181012_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lg_user', models.CharField(max_length=64, unique=True)),
                ('lg_passwd', models.CharField(max_length=256, null=True)),
                ('lg_key', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auth.User')),
            ],
        ),
    ]
