# Generated by Django 2.1.1 on 2018-10-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0008_remoteuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perms',
            name='perms_url',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
