# Generated by Django 2.1.1 on 2018-10-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0008_auto_20181008_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perms',
            name='perms',
            field=models.CharField(choices=[('get', '查'), ('post', '增'), ('delete', '删'), ('put', '改')], max_length=64),
        ),
    ]
