# Generated by Django 2.1.1 on 2018-10-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0009_auto_20181024_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='menu_url',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
