# Generated by Django 2.1.1 on 2018-10-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0010_auto_20181024_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteuser',
            name='lg_key_pass',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='menus',
            name='menu_url',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
