# Generated by Django 2.1.1 on 2018-10-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0012_menus_menus_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='menus_order',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
