# Generated by Django 2.1.1 on 2018-10-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0013_auto_20181008_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menus',
            old_name='menus_icon',
            new_name='menu_icon',
        ),
        migrations.RenameField(
            model_name='menus',
            old_name='menus_id',
            new_name='menu_id',
        ),
        migrations.RenameField(
            model_name='menus',
            old_name='menus_order',
            new_name='menu_order',
        ),
        migrations.RenameField(
            model_name='menus',
            old_name='menus_title',
            new_name='menu_title',
        ),
        migrations.RenameField(
            model_name='menus',
            old_name='menus_url',
            new_name='menu_url',
        ),
    ]
