# Generated by Django 2.1.1 on 2018-10-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0015_menus_menu_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='parent',
        ),
        migrations.AddField(
            model_name='menus',
            name='pmenu_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
