# Generated by Django 2.1.1 on 2018-10-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0016_auto_20181008_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menus',
            old_name='menu_id',
            new_name='menu_num',
        ),
        migrations.AlterField(
            model_name='menus',
            name='menu_url',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='menus',
            name='pmenu_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
